/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.Connection.ConnectionMessageClient');
goog.provide('proto.Connection.ConnectionMessageClient.ConnectionMessageTypeClient');

goog.require('jspb.Message');
goog.require('proto.Connection.StartMatchMaking');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Connection.ConnectionMessageClient = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Connection.ConnectionMessageClient, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Connection.ConnectionMessageClient.displayName = 'proto.Connection.ConnectionMessageClient';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Connection.ConnectionMessageClient.prototype.toObject = function(opt_includeInstance) {
  return proto.Connection.ConnectionMessageClient.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Connection.ConnectionMessageClient} msg The msg instance to transform.
 * @return {!Object}
 */
proto.Connection.ConnectionMessageClient.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getField(msg, 1),
    startmatchmaking: (f = msg.getStartmatchmaking()) && proto.Connection.StartMatchMaking.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.Connection.ConnectionMessageClient} The clone.
 */
proto.Connection.ConnectionMessageClient.prototype.cloneMessage = function() {
  return /** @type {!proto.Connection.ConnectionMessageClient} */ (jspb.Message.cloneMessage(this));
};


/**
 * required ConnectionMessageTypeClient type = 1;
 * @return {!proto.Connection.ConnectionMessageClient.ConnectionMessageTypeClient}
 */
proto.Connection.ConnectionMessageClient.prototype.getType = function() {
  return /** @type {!proto.Connection.ConnectionMessageClient.ConnectionMessageTypeClient} */ (!this.hasType() ? 0 : jspb.Message.getField(this, 1));
};


/** @param {proto.Connection.ConnectionMessageClient.ConnectionMessageTypeClient|undefined} value  */
proto.Connection.ConnectionMessageClient.prototype.setType = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.Connection.ConnectionMessageClient.prototype.clearType = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.Connection.ConnectionMessageClient.prototype.hasType = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional StartMatchMaking startMatchMaking = 2;
 * @return {proto.Connection.StartMatchMaking}
 */
proto.Connection.ConnectionMessageClient.prototype.getStartmatchmaking = function() {
  return /** @type{proto.Connection.StartMatchMaking} */ (
    jspb.Message.getWrapperField(this, proto.Connection.StartMatchMaking, 2));
};


/** @param {proto.Connection.StartMatchMaking|undefined} value  */
proto.Connection.ConnectionMessageClient.prototype.setStartmatchmaking = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.Connection.ConnectionMessageClient.prototype.clearStartmatchmaking = function() {
  this.setStartmatchmaking(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.Connection.ConnectionMessageClient.prototype.hasStartmatchmaking = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * @enum {number}
 */
proto.Connection.ConnectionMessageClient.ConnectionMessageTypeClient = {
  START_MATCH_MAKING: 0,
  STOP_MATCH_MAKING: 1,
  READY: 2
};

