/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.Connection.ConnectionMessageServer');
goog.provide('proto.Connection.ConnectionMessageServer.ConnectionMessageTypeServer');

goog.require('jspb.Message');
goog.require('proto.Connection.ACKMM');
goog.require('proto.Connection.StartGame');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Connection.ConnectionMessageServer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Connection.ConnectionMessageServer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Connection.ConnectionMessageServer.displayName = 'proto.Connection.ConnectionMessageServer';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Connection.ConnectionMessageServer.prototype.toObject = function(opt_includeInstance) {
  return proto.Connection.ConnectionMessageServer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Connection.ConnectionMessageServer} msg The msg instance to transform.
 * @return {!Object}
 */
proto.Connection.ConnectionMessageServer.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getField(msg, 1),
    ackmm: (f = msg.getAckmm()) && proto.Connection.ACKMM.toObject(includeInstance, f),
    startgame: (f = msg.getStartgame()) && proto.Connection.StartGame.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.Connection.ConnectionMessageServer} The clone.
 */
proto.Connection.ConnectionMessageServer.prototype.cloneMessage = function() {
  return /** @type {!proto.Connection.ConnectionMessageServer} */ (jspb.Message.cloneMessage(this));
};


/**
 * required ConnectionMessageTypeServer type = 1;
 * @return {!proto.Connection.ConnectionMessageServer.ConnectionMessageTypeServer}
 */
proto.Connection.ConnectionMessageServer.prototype.getType = function() {
  return /** @type {!proto.Connection.ConnectionMessageServer.ConnectionMessageTypeServer} */ (!this.hasType() ? 1 : jspb.Message.getField(this, 1));
};


/** @param {proto.Connection.ConnectionMessageServer.ConnectionMessageTypeServer|undefined} value  */
proto.Connection.ConnectionMessageServer.prototype.setType = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.Connection.ConnectionMessageServer.prototype.clearType = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.Connection.ConnectionMessageServer.prototype.hasType = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ACKMM ackmm = 2;
 * @return {proto.Connection.ACKMM}
 */
proto.Connection.ConnectionMessageServer.prototype.getAckmm = function() {
  return /** @type{proto.Connection.ACKMM} */ (
    jspb.Message.getWrapperField(this, proto.Connection.ACKMM, 2));
};


/** @param {proto.Connection.ACKMM|undefined} value  */
proto.Connection.ConnectionMessageServer.prototype.setAckmm = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.Connection.ConnectionMessageServer.prototype.clearAckmm = function() {
  this.setAckmm(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.Connection.ConnectionMessageServer.prototype.hasAckmm = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional StartGame startGame = 3;
 * @return {proto.Connection.StartGame}
 */
proto.Connection.ConnectionMessageServer.prototype.getStartgame = function() {
  return /** @type{proto.Connection.StartGame} */ (
    jspb.Message.getWrapperField(this, proto.Connection.StartGame, 3));
};


/** @param {proto.Connection.StartGame|undefined} value  */
proto.Connection.ConnectionMessageServer.prototype.setStartgame = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.Connection.ConnectionMessageServer.prototype.clearStartgame = function() {
  this.setStartgame(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.Connection.ConnectionMessageServer.prototype.hasStartgame = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * @enum {number}
 */
proto.Connection.ConnectionMessageServer.ConnectionMessageTypeServer = {
  ACK_MATCH_MAKING: 1,
  MATCH_FOUND: 2,
  START_GAME: 3
};

